"""create tables

Revision ID: 53b2621ec82a
Revises: 
Create Date: 2025-06-03 22:43:11.093182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b2621ec82a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
